"""Plot FP/FN asymmetry curve for SAT n=50 oracle-lookahead corruption.

This figure shows the "precision cliff": how solve rate degrades as the
verifier's false-positive rate increases vs. its false-negative rate, with
an MLP policy under oracle look-ahead verification on SAT n=50.

The ``fp_solve_rate`` / ``fn_solve_rate`` arrays below are the measured
solve rates (%) from the SAT n=50 corruption-curve experiment. They are
regenerated by running:

    PYTHONPATH=src python scripts/evaluation/eval_corruption_curve.py \
        --mode sweep --fp_rate 0.0,0.05,0.1,0.15,0.2,0.3,0.4,0.5 \
        --fn_rate 0.0,0.05,0.1,0.15,0.2,0.3,0.4,0.5 \
        --output_dir experiments/fp-fn-decomposition

and pulling ``solve_rate`` per configuration from the resulting JSONs.

Note: This is the CSP (SAT) precision-cliff data, *not* the LLM FP/FN
asymmetry data in paper table tab_llm_fpfn. The latter comes from
``scripts/llm/analyze_fpfn_stratified.py`` applied to Qwen-14B / Qwen-4B
candidate files.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from pathlib import Path


def create_plot():
    # Set matplotlib parameters for a clean, academic Springer-style plot
    mpl.rcParams["font.size"] = 10
    mpl.rcParams["axes.labelsize"] = 10
    mpl.rcParams["xtick.labelsize"] = 9
    mpl.rcParams["ytick.labelsize"] = 9
    mpl.rcParams["legend.fontsize"] = 9
    mpl.rcParams["axes.linewidth"] = 0.8
    mpl.rcParams["xtick.major.width"] = 0.8
    mpl.rcParams["ytick.major.width"] = 0.8
    mpl.rcParams["xtick.direction"] = "out"
    mpl.rcParams["ytick.direction"] = "out"
    mpl.rcParams["pdf.fonttype"] = 42  # TrueType fonts for PDF
    mpl.rcParams["ps.fonttype"] = 42
    mpl.rcParams["font.family"] = "sans-serif"
    mpl.rcParams["font.sans-serif"] = ["Helvetica", "Arial", "DejaVu Sans"]

    # Data
    rates = np.array([0.0, 1.0, 2.0, 5.0, 10.0, 15.0, 20.0, 30.0, 40.0, 50.0])

    fp_solve_rate = np.array(
        [100.0, 100.0, 99.0, 96.0, 88.6, 70.5, 55.9, 17.4, 3.5, 0.0]
    )
    fn_solve_rate = np.array(
        [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
    )

    # Theoretical prediction (smooth curve based on formula)
    x_theo = np.linspace(0, 50, 100)
    y_theo = ((1.0 - x_theo / 100.0) ** 20) * 100.0

    # Figure setup (3.5 inches width is roughly 0.65\textwidth for single column)
    fig, ax = plt.subplots(figsize=(3.5, 2.6))

    # Plot lines
    ax.plot(
        rates,
        fn_solve_rate,
        marker="s",
        markersize=5,
        color="#1f77b4",
        linestyle="-",
        linewidth=1.5,
        label="False negative",
    )

    ax.plot(
        rates,
        fp_solve_rate,
        marker="o",
        markersize=5,
        color="#d62728",
        linestyle="-",
        linewidth=1.5,
        label="False positive",
    )

    ax.plot(
        x_theo,
        y_theo,
        color="#7f7f7f",
        linestyle="--",
        linewidth=1.5,
        label=r"$(1-\alpha)^{M}$, $M{=}20$",
    )

    # Axis labels
    ax.set_xlabel("Injection rate (%)")
    ax.set_ylabel("Solve rate (%)")

    # Axis limits
    ax.set_xlim(-2, 52)
    ax.set_ylim(-5, 105)

    # Clean axes: no top/right spines, no grid
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(False)

    # Legend positioning (right side middle, avoiding data lines)
    ax.legend(loc="center right", frameon=False, bbox_to_anchor=(0.98, 0.45))

    # Layout adjustment
    plt.tight_layout()

    # Save output
    output_path = Path("fp_fn_asymmetry.pdf")
    plt.savefig(output_path, format="pdf", bbox_inches="tight")
    print(f"Successfully saved plot to {output_path}")


if __name__ == "__main__":
    create_plot()
